---
title: "manipulation"
author: "Paulina Han"
date: "2021/9/28"
output: html_document
---

```{r, echo=FALSE, message=FALSE}
library(tidyverse)

```


##import data

i want to import `FAS_litters.csv`.

```{r}
litters_df=read_csv('data/data_import_examples/FAS_litters.csv') #re;active
litters_df = janitor::clean_names(litters_df)

pups_data = read_csv("data/data_import_examples//FAS_pups.csv")
pups_data = janitor::clean_names(pups_data)

```

## `select`

```{r}
select(litters_df,group,litter_number)
select(litters_df, group,gd0_weight:gd_of_birth)
```


## `filter`
```{r}
filter(litters_df,gd_of_birth == 20)
filter(litters_df, group == "Con7")

filter(litters_df, gd0_weight < 23)


filter(litters_df,!(group == 'Con7'))

filter(litters_df,group%in%c("Con7","Con8"))

filter(litters_df, group == "Con7", gd_of_birth ==20)
```

```{r}

drop_na(litters_df)
drop_na(litters_df,gd0_weight)
```


## mutate

```{r}
mutate(litters_df,
       weight_change = gd18_weight - gd0_weight,
       group = str_to_lower(group))
```
## arrange
```{r}
arrange(litters_df, gd_of_birth, gd0_weight)
```

## Pipes
```{r}
litters_data_raw = read_csv("data/data_import_examples/FAS_litters.csv")
litters_clean_names = janitor::clean_names(litters_data_raw)
litters_select = select(litters_clean_names,groups,pup_survive)
litters_filtered = filter(litters_select, group == "Con7")


litters_df =
  read_csv("data/data_import_examples/FAS_litters.csv") %>%
  janitor::clean_names()%>%
  select(group, pups_survive)%>%
  filter(group == "Con7")

litters_df =
  read_csv("data/data_import_examples/FAS_litters.csv") %>%
  janitor::clean_names()%>%
  select(-pups_survive)%>%
  mutate(
    weight_change = gd18_weight - gd0_weight,
    group = str_to_lower(group)
  ) %>% 
  drop_na(weight_change) %>% 
  filter(group %in% c("con7","con8")) %>% 
  select(litter_number,group,weight_change,everything())

```



