---
title: "Simple document"
output: github_document
---

```{r, echo=FALSE, message=FALSE}
library(tidyverse)

```


##import data

i want to import `FAS_litters.csv`.

```{r}
litters_df=read.csv('data/data_import_examples/FAS_litters.csv') #re;ative

#relative path always gonna work; the direct path doesn't work if you share the the R and data
```

```{r}
names(litters_df)

litters_df = janitor::clean_names(litters_df) #only load clean_names

tibble(litters_df)#show the typw of var
```
one I use a lot

```{r, eval=FALSE}
view(litters_df)

```

here is skier
```{r}
skimr::skim(litters_df)

```
## arguments in "read.csv"

```{r, }
litters_df =
  read_csv("data/data_import_examples/FAS_litters.csv",
           skip= 5,
           col_names=F,
           na = "Low8")
```


## reading EXCEL
```{r}
library(readxl)
mlb11_df =read_excel("data/data_import_examples/mlb11.xlsx")
```


## read a small block

```{r}
fellow_df = read_excel("data/data_import_examples/LotR_Words.xlsx", range = "B3:D6")

```

## read SAS
```{r}
library(haven)
pulse_df = read_sas("./data/data_import_examples/public_pulse_data.sas7bdat",encoding = "latin1")

```

